spring:
  profiles:
    active: dev
multipart:
  maxFileSize: 512MB
  maxRequestSize: 512MB
  fileSizeThreshold: 512MB
tika:
  mediaType: text/plain,application/xml,text/html,text/csv
  maxStringLength: -1
reindex:
  bulkActions: 1000
  flushInterval: 5
  bulkSize: 5